### ISSUE TITLE
Check existing RELEASE_NOTES.md

### ISSUE THREAD

**Issue by Freymaurer** [kMutagene/BuildProject#1]
Loving this template, so i got a suggestion to smoothen the set up.

Normally i use this to set up a new project with testing, etc. and i noticed that you cannot run any tasks without an existing `RELEASE_NOTES.md` with some minimal info. 

Why not add something like this to the `ProjectInfo.fs` before loading the release notes file:

```fsharp
let exists() =
    let isExisting = Fake.IO.File.exists "RELEASE_NOTES.md"
    if isExisting = false then
        Fake.IO.File.create "RELEASE_NOTES.md"
        Fake.IO.File.write
            true
            "RELEASE_NOTES.md"
            [
                sprintf "### 0.0.0 (Released %s)" (createCurrentDateString())
                "* Additions:"
                "    * Initial set up for RELEASE_Notes.md"
            ]
        Trace.traceImportant "RELEASE_Notes.md created"
    else
        Trace.trace "RELEASE_Notes.md found"
```

Or use the [following](https://github.com/Freymaurer/Fake.Extensions.Release):
```fsharp
Release.exists()
```

**Comment by kMutagene** [comment]
The issue with not enforcing a readme is that all versioning info for packages etc. is also taken from the version string in the release notes. 

Regarding naming of your function: i would expect `Release.exists()` to return true or false, and not do anything else. I would suggest changing the name to `Release.ensure()` (see FAKE equivalent for Directories https://github.com/fsprojects/FAKE/blob/master/src/app/Fake.IO.FileSystem/Directory.fs#L9-9)

Generally, i think we could integrate https://github.com/Freymaurer/Fake.Extensions.Release into this template anyways.

**Comment by Freymaurer** [comment]
> The issue with not enforcing a readme is that all versioning info for packages etc. is also taken from the version string in the release notes.

Sorry I don't know what you are referring to here.😅 

> Regarding naming of your function: i would expect Release.exists() to return true or false, and not do anything else. I would suggest changing the name to Release.ensure() (see FAKE equivalent for Directories https://github.com/fsprojects/FAKE/blob/master/src/app/Fake.IO.FileSystem/Directory.fs#L9-9)

You are right, i will change the naming!

**Comment by Freymaurer** [comment]
Okay! So i finally fixed the SemVer parsing issue in FAKE and used some time this weekend to update Fake.Extensions.Release to be a bit more robust.

`ReleaseNotes.ensure()` will check if RELEASE_NOTES.md exists, and if not create one with a minimal text info.
`ReleaseNotes.update(..)` handles updating the RELEASE_NOTES.md according to git commits done in the active repository.

Should you need some more information @kMutagene , i am more than happy to help, as i currently use your template for all my repos and always have to add release note handling by hand. 😅

**Comment by kMutagene** [comment]
@Freymaurer feel free to add a PR with the respective BuildTasks
